#!/bin/sh
### BEGIN INIT INFO
# Provides:          chatapp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start chat app
# Description:       Starts, stops, and restarts the chat app
### END INIT INFO

APP_NAME="chat-server"
APP_CMD="/usr/bin/chat-server"
PIDFILE="/var/run/$APP_NAME.pid"
LOGFILE="/var/log/$APP_NAME.log"

case "$1" in
    start)
        echo "Starting $APP_NAME..."
        if [ -f $PIDFILE ]; then
            echo "$APP_NAME is already running."
            exit 1
        fi
        nohup $APP_CMD >> $LOGFILE 2>&1 &
        echo $! > $PIDFILE
        echo "$APP_NAME started."
        ;;
    stop)
        echo "Stopping $APP_NAME..."
        if [ ! -f $PIDFILE ]; then
            echo "$APP_NAME is not running."
            exit 1
        fi
        kill $(cat $PIDFILE)
        rm -f $PIDFILE
        echo "$APP_NAME stopped."
        ;;
    restart)
        echo "Restarting $APP_NAME..."
        $0 stop
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ]; then
            echo "$APP_NAME is running (pid $(cat $PIDFILE))"
        else
            echo "$APP_NAME is not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
